/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DBService.BestellungHelper;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author fixch
 */
public class AdressenScreen extends javax.swing.JFrame {

    /**
     * Creates new form AdressenScreen
     */
    private double gesamtpreisAllerArtikel = 0.0;
    private final HashMap<Integer, Integer> alleBestellenArtikel;
    public AdressenScreen(double gesamtpreisAllerArtikel, HashMap<Integer, Integer> bestellteArtikel) {
        initComponents();
        this.gesamtpreisAllerArtikel = gesamtpreisAllerArtikel;
        this.alleBestellenArtikel = bestellteArtikel;
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LB_Adresse = new javax.swing.JLabel();
        BT_Bestellen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LB_Adresse.setText("Bitte wählen Sie Ihre Adresse");

        BT_Bestellen.setText("Bestellen");
        BT_Bestellen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_BestellenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(LB_Adresse)
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BT_Bestellen)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LB_Adresse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                .addComponent(BT_Bestellen)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_BestellenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_BestellenActionPerformed
        if(BestellungHelper.insertBestellung(1, this.alleBestellenArtikel)) //Bestellung erfolgreich in die DB eingetragen
        {
            JOptionPane.showMessageDialog(this, "Ihre Bestellung wurde erfolgreich gespeichert");
            this.setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Ihre Bestellung konnte leider nicht gespeichert werden");
        }
       

//Rechnung in Datenbank einfügen
        //INSERT INTO "Rechnung" (fk_user_adresse) VALUES (1);
        //INSERT INTO "RechnungArtikel" (fk_rechnung, fk_artikel, anzahl) VALUES (1, 1, 1);
        //Rechnung anzeigen
        //SELECT * FROM v_BestellungenAnzeigen WHERE "RechnungID" = 1
    }//GEN-LAST:event_BT_BestellenActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_Bestellen;
    private javax.swing.JLabel LB_Adresse;
    // End of variables declaration//GEN-END:variables
}
