/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import model.Artikel;

/**
 *
 * @author lenzch
 */
public class ArtikelDetails extends javax.swing.JFrame {

    private Artikel artikel;
         
    public ArtikelDetails(Artikel artikel) {
        initComponents();  
        
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        this.artikel = artikel;
        //System.out.println(artikel.getName());
        this.LB_ArtikelName.setText(artikel.getName());
        this.LB_ArtikelBeschreibung.setText(artikel.getBeschreibung());
        //this.LB_ArtikelPreis.setText(artikel.g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        LB_ArtikelName = new javax.swing.JLabel();
        LB_ArtikelBeschreibung = new javax.swing.JLabel();
        TB_ArtikelMenge = new javax.swing.JTextField();
        LB_ArtikelMenge = new javax.swing.JLabel();
        LB_ArtikelPreis = new javax.swing.JLabel();
        BT_Warenkorb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LB_ArtikelName.setText("ArtikelName");

        LB_ArtikelBeschreibung.setText("ArtikelBeschreibung");

        TB_ArtikelMenge.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                TB_ArtikelMengeInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        LB_ArtikelMenge.setText("Menge");

        LB_ArtikelPreis.setText("Preis");

        BT_Warenkorb.setText("In Warenkorb");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BT_Warenkorb)
                        .addComponent(LB_ArtikelBeschreibung)
                        .addComponent(LB_ArtikelName))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LB_ArtikelMenge)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TB_ArtikelMenge, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(LB_ArtikelPreis)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(LB_ArtikelName)
                .addGap(42, 42, 42)
                .addComponent(LB_ArtikelBeschreibung)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TB_ArtikelMenge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_ArtikelMenge)
                    .addComponent(LB_ArtikelPreis))
                .addGap(37, 37, 37)
                .addComponent(BT_Warenkorb)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void TB_ArtikelMengeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {                                                       
        // TODO add your handling code here:
    }                                                      

    // Variables declaration - do not modify                     
    private javax.swing.JButton BT_Warenkorb;
    private javax.swing.JLabel LB_ArtikelBeschreibung;
    private javax.swing.JLabel LB_ArtikelMenge;
    private javax.swing.JLabel LB_ArtikelName;
    private javax.swing.JLabel LB_ArtikelPreis;
    private javax.swing.JTextField TB_ArtikelMenge;
    // End of variables declaration                   
}
