/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DBService.ArtikelHelper;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Artikel;
import model.ArtikelTableModel;

/**
 *
 * @author lenzch
 */
public class HauptScreen extends javax.swing.JFrame {

    /**
     * Creates new form HauptScreen
     */
    public HauptScreen() throws SQLException {
        initComponents();
        //TBL_Artikel.
        this.TBL_Artikel.setModel(new ArtikelTableModel());       
        //int index = this.TBL_Artikel.getSelectedRow();
        //System.out.println(index);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BT_NeuerArtikel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBL_Artikel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BT_NeuerArtikel.setText("neuer Artikel");
        BT_NeuerArtikel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_NeuerArtikelActionPerformed(evt);
            }
        });

        TBL_Artikel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TBL_Artikel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TBL_ArtikelFocusGained(evt);
            }
        });
        TBL_Artikel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBL_ArtikelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBL_Artikel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BT_NeuerArtikel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(BT_NeuerArtikel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_NeuerArtikelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_NeuerArtikelActionPerformed
            setVisible(false);
        try {
            new ArtikelForm().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(HauptScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BT_NeuerArtikelActionPerformed

    private void TBL_ArtikelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TBL_ArtikelFocusGained
        // TODO add your handling code here:
        //int index = this.TBL_Artikel.getSelectedRow();
        //System.out.println(index);
    }//GEN-LAST:event_TBL_ArtikelFocusGained

    private void TBL_ArtikelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBL_ArtikelMouseClicked
        // TODO add your handling code here:
        int index = this.TBL_Artikel.getSelectedRow();
        System.out.println(index);
        
        if(evt.getClickCount() >= 2) {
            try {                
                int id = (int) this.TBL_Artikel.getModel().getValueAt(index, 0);
                Artikel artikel = ArtikelHelper.getArticle(id);

                new ArtikelDetails(artikel).setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(HauptScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            //System.out.println("Doppelklick auf: " + index);
        }
    }//GEN-LAST:event_TBL_ArtikelMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_NeuerArtikel;
    private javax.swing.JTable TBL_Artikel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
