/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author fixch
 */
public class PanelArtikel extends javax.swing.JPanel {

    /**
     * Creates new form PanelArtikel
     * @param artikelName
     * @param anzahl
     */
    public PanelArtikel(String artikelName, int bruttoPreisInCent, int anzahl) {
        initComponents();
        
        if("".equals(artikelName.trim()) && bruttoPreisInCent <= 0 && anzahl <= 0)
        {
            JOptionPane.showMessageDialog(this, "Falsche Übergabeparameter an PanelArtikel");
            this.LB_Artikelname.setText("Es ist ein Fehler aufgetreten");
        }
        
        this.LB_Artikelname.setText(artikelName);
        this.SPINNER_Anzahl.setValue(anzahl);
        
        double bruttoPreisInEuro = 0;
        try
        {
            bruttoPreisInEuro = (double)(bruttoPreisInCent / 100d);
        }
        catch(Exception ex)
        {
            bruttoPreisInEuro = 0;
        }
        if(bruttoPreisInEuro != 0)
        {
            System.out.println(bruttoPreisInEuro + "€");
            this.LB_Bruttopreis.setText(String.valueOf(bruttoPreisInEuro));
        }
        
        double gesamtPreis = 0;
        if(anzahl > 0 && bruttoPreisInEuro > 0)
        {
            gesamtPreis = rundeKorrektInEuro(bruttoPreisInEuro * anzahl);
        }
                
        this.LB_Gesamtpreis.setText(String.valueOf(gesamtPreis));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LB_Artikelname = new javax.swing.JLabel();
        SPINNER_Anzahl = new javax.swing.JSpinner();
        LB_Bruttopreis = new javax.swing.JLabel();
        LB_Gesamtpreis = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LB_Artikelname.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N

        SPINNER_Anzahl.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SPINNER_AnzahlStateChanged(evt);
            }
        });

        LB_Bruttopreis.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        LB_Gesamtpreis.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LB_Artikelname, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPINNER_Anzahl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(LB_Bruttopreis, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(LB_Gesamtpreis, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SPINNER_Anzahl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LB_Bruttopreis, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LB_Artikelname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(LB_Gesamtpreis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SPINNER_AnzahlStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SPINNER_AnzahlStateChanged
        if(!"".equals(this.LB_Bruttopreis.getText()) && this.SPINNER_Anzahl.getValue() != "")
        {
            double bruttopreis = Double.parseDouble(this.LB_Bruttopreis.getText());
            int anzahl = (int) this.SPINNER_Anzahl.getValue();
            double gesamtpreis = rundeKorrektInEuro(bruttopreis * anzahl);
            this.LB_Gesamtpreis.setText(String.valueOf(gesamtpreis));
        }
    }//GEN-LAST:event_SPINNER_AnzahlStateChanged

    //behebt Probleme mit Fließkommazahlen
    private double rundeKorrektInEuro(double eingabe)
    {
        eingabe = eingabe * 100;
        eingabe = Math.round(eingabe);
        return eingabe / 100;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LB_Artikelname;
    private javax.swing.JLabel LB_Bruttopreis;
    private javax.swing.JLabel LB_Gesamtpreis;
    private javax.swing.JSpinner SPINNER_Anzahl;
    // End of variables declaration//GEN-END:variables
}
