/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DBService.BenutzerHelper;
import DBService.UserAdresseHelper;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.User;
import model.UserAdresseTableModel;

/**
 *
 * @author Christopher
 */
public class UserAdresseScreen extends javax.swing.JFrame {

    /**
     * Creates new form UserAdresseScreen
     */
    public UserAdresseScreen() throws SQLException {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        this.TBL_UserAdresse.setModel(new UserAdresseTableModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TBL_UserAdresse = new javax.swing.JTable();
        LBL_vorname = new javax.swing.JLabel();
        TF_vorname = new javax.swing.JTextField();
        LBL_nachname = new javax.swing.JLabel();
        TF_nachname = new javax.swing.JTextField();
        TF_adresse = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BT_löschen = new javax.swing.JButton();
        TF_hausnummer = new javax.swing.JTextField();
        TF_plz = new javax.swing.JTextField();
        LBL_hausnummer = new javax.swing.JLabel();
        LBL_plz = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TBL_UserAdresse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TBL_UserAdresse);

        LBL_vorname.setText("Vorname");

        TF_vorname.setText(" ");

        LBL_nachname.setText("Nachname");

        jLabel1.setText("Anschrift");

        jButton1.setText("Hinzufügen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BT_löschen.setText("Löschen");
        BT_löschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_löschenActionPerformed(evt);
            }
        });

        TF_plz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_plzActionPerformed(evt);
            }
        });

        LBL_hausnummer.setText("Hausnr.");

        LBL_plz.setText("PLZ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TF_hausnummer)
                                .addGap(18, 18, 18)
                                .addComponent(TF_plz, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(418, 418, 418))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LBL_vorname)
                                            .addComponent(TF_vorname, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TF_nachname, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LBL_nachname))
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(TF_adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton1)
                                                .addGap(18, 18, 18)
                                                .addComponent(BT_löschen))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LBL_hausnummer)
                                        .addGap(18, 18, 18)
                                        .addComponent(LBL_plz)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(0, 34, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_vorname)
                    .addComponent(LBL_nachname)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_vorname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_nachname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_adresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(BT_löschen))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_hausnummer)
                    .addComponent(LBL_plz))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_hausnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_plz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            if(!istNummmer(TF_plz.getText())) {
                JOptionPane.showMessageDialog(this, "Für die PLZ bitte eine Zahl eingeben!");
                return;
            }
            
            String vorname = TF_vorname.getText().trim();
            String nachname = TF_nachname.getText().trim();
            String anschrift = TF_adresse.getText();
            int hausnummer = Integer.parseInt(TF_hausnummer.getText());             
            int plz = Integer.parseInt(TF_plz.getText());
            
            User user = User.GetInstance();            
            UserAdresseHelper.insertUserAdresse(user.getId(), user.getName(), vorname, nachname, anschrift, hausnummer, plz);       
            refreshUserAdresseTabelle();
            
        } catch (SQLException ex) {
            Logger.getLogger(UserAdresseScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public static boolean istNummmer(String str)
    {
      return str.matches("[0123456789]*");  
    }
    
    private void BT_löschenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_löschenActionPerformed
        // TODO add your handling code here:
        int selectedRowId = this.TBL_UserAdresse.getSelectedRow();
        int UserAdresse = -1;
        if (selectedRowId != -1) {
            BT_löschen.setEnabled(true);
            UserAdresse = (int) this.TBL_UserAdresse.getModel().getValueAt(selectedRowId, 0);
            if (UserAdresse != -1) {                
                UserAdresseHelper.deleteUserAdresse(UserAdresse);
                refreshUserAdresseTabelle();
            } else {
                JOptionPane.showMessageDialog(this, "Fehler: Der selektiere Benutzer konnte nicht in der Datenbank gefunden werden");
            }
        }
    }//GEN-LAST:event_BT_löschenActionPerformed

    private void TF_plzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_plzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_plzActionPerformed

    private void refreshUserAdresseTabelle() {
        try {
            this.TBL_UserAdresse.setModel(new UserAdresseTableModel());           
        } catch (SQLException ex) {
            Logger.getLogger(UserAdresseScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserAdresseScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserAdresseScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserAdresseScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserAdresseScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new UserAdresseScreen().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(UserAdresseScreen.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_löschen;
    private javax.swing.JLabel LBL_hausnummer;
    private javax.swing.JLabel LBL_nachname;
    private javax.swing.JLabel LBL_plz;
    private javax.swing.JLabel LBL_vorname;
    private javax.swing.JTable TBL_UserAdresse;
    private javax.swing.JTextField TF_adresse;
    private javax.swing.JTextField TF_hausnummer;
    private javax.swing.JTextField TF_nachname;
    private javax.swing.JTextField TF_plz;
    private javax.swing.JTextField TF_vorname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
