/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Warenkorb;
import model.WarenkorbTableModel;

/**
 *
 * @author fixch
 */
public class WarenkorbScreen extends javax.swing.JFrame {

    /**
     * Creates new form WarenkorbScreen
     *
     * @throws java.sql.SQLException
     */
    public WarenkorbScreen() throws SQLException {
        initComponents();
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        if (Warenkorb.GetInstance().getGesamtbruttopreisAllerArtikel() > 0) {
            this.BT_Kaufen.setEnabled(true);
        } else {
            this.BT_Kaufen.setEnabled(false);
        }
        this.TBL_Warenkorb.setModel(new WarenkorbTableModel(Warenkorb.GetInstance().getWarenkorbinhalt()));
        this.LB_GesamtpreisAllerArtikel.setText(Warenkorb.GetInstance().getGesamtbruttopreisAllerArtikel() + " €");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LB_Warenkorb = new javax.swing.JLabel();
        PANEL_Gesamt = new javax.swing.JPanel();
        LB_SUM_Gesamtpreis = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBL_Warenkorb = new javax.swing.JTable();
        BT_Kaufen = new javax.swing.JButton();
        LB_GesamtpreisAllerArtikel = new javax.swing.JLabel();
        BT_Leeren = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 769));

        LB_Warenkorb.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        LB_Warenkorb.setText("Warenkorb");

        javax.swing.GroupLayout PANEL_GesamtLayout = new javax.swing.GroupLayout(PANEL_Gesamt);
        PANEL_Gesamt.setLayout(PANEL_GesamtLayout);
        PANEL_GesamtLayout.setHorizontalGroup(
            PANEL_GesamtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANEL_GesamtLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LB_SUM_Gesamtpreis, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PANEL_GesamtLayout.setVerticalGroup(
            PANEL_GesamtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_GesamtLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(LB_SUM_Gesamtpreis, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TBL_Warenkorb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TBL_Warenkorb.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TBL_WarenkorbPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(TBL_Warenkorb);

        BT_Kaufen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BT_Kaufen.setText("Kaufen");
        BT_Kaufen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_KaufenActionPerformed(evt);
            }
        });

        LB_GesamtpreisAllerArtikel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LB_GesamtpreisAllerArtikel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LB_GesamtpreisAllerArtikel.setText("0.00 €");

        BT_Leeren.setText("Warenkorb leeren");
        BT_Leeren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_LeerenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LB_GesamtpreisAllerArtikel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(BT_Kaufen, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addComponent(LB_Warenkorb)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BT_Leeren))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PANEL_Gesamt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LB_Warenkorb))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BT_Leeren)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PANEL_Gesamt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BT_Kaufen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LB_GesamtpreisAllerArtikel)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_KaufenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_KaufenActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Wollen Sie die/den Artikel für " + this.LB_GesamtpreisAllerArtikel.getText() + " bestellen?") == 0) //Ja
        {
            try {
                AdressenScreen adressenScreen = new AdressenScreen(Warenkorb.GetInstance().getGesamtbruttopreisAllerArtikel(), Warenkorb.GetInstance().getWarenkorbinhalt());
                this.setVisible(false);
                adressenScreen.setVisible(true);
                adressenScreen.setResizable(false);
                adressenScreen.setLocationRelativeTo(null);
            } catch (SQLException ex) {
                Logger.getLogger(WarenkorbScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_BT_KaufenActionPerformed

    private void TBL_WarenkorbPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TBL_WarenkorbPropertyChange
        try {
            this.LB_GesamtpreisAllerArtikel.setText(Warenkorb.GetInstance().getGesamtbruttopreisAllerArtikel() + " €");
            if (Warenkorb.GetInstance().getGesamtbruttopreisAllerArtikel() <= 0) {
                this.BT_Kaufen.setEnabled(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(WarenkorbScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TBL_WarenkorbPropertyChange

    private void BT_LeerenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_LeerenActionPerformed
        Object[] alleIDs = Warenkorb.GetInstance().getWarenkorbinhalt().keySet().toArray();
        for (Object id : alleIDs) {
            Warenkorb.GetInstance().removeArtikel((int) id);
        }
        this.TBL_Warenkorb.setModel(new WarenkorbTableModel(Warenkorb.GetInstance().getWarenkorbinhalt()));
        this.BT_Kaufen.setEnabled(false);

    }//GEN-LAST:event_BT_LeerenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_Kaufen;
    private javax.swing.JButton BT_Leeren;
    private javax.swing.JLabel LB_GesamtpreisAllerArtikel;
    private javax.swing.JLabel LB_SUM_Gesamtpreis;
    private javax.swing.JLabel LB_Warenkorb;
    private javax.swing.JPanel PANEL_Gesamt;
    private javax.swing.JTable TBL_Warenkorb;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
